features:
  creative_inventory_integration: true
  custom_paintings: true

behaviours:
  bed: true
  connectable: true
  contact_damage: true
  stackable: true
  storage: true
  text_display: true

actions:
  actionbar: true
  clear_item: true
  ignite: true
  message: true
  mythic_mobs_skill: true
  open_inventory: true
  play_animation: true
  play_emote: true
  replace_biome: true
  shoot_fireball: true
  swing_hand: true
  teleport: true
  title: true
  toast: true
  veinminer: true

update-checker:
  enabled: true
  on-join: true
