actions:
  actionbar: true
  clear_item: true
  message: true
  open_inventory: true
  play_animation: true
  play_emote: true
  swing_hand: true
  teleport: true
  title: true
  toast: true
  veinminer: true

behaviours:
  connectable: true
  contact_damage: true
  stackable: true

features:
  creative_inventory_integration: false
