name: ItemsAdderAdditions
version: '${version}'
main: toutouchien.itemsadderadditions.ItemsAdderAdditions
bootstrapper: toutouchien.itemsadderadditions.ItemsAdderAdditionsBootstrap
api-version: '${minMinecraftVersion}'
authors: [ PuppyTransGirl ]

dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: true

    PlaceholderAPI:
      load: BEFORE
      required: false
