package toutouchien.itemsadderadditions.integration.valhalla;

import org.jspecify.annotations.NullMarked;

import java.util.Arrays;
import java.util.Set;

@NullMarked
final class ValhallaKnownValues {
    static final Set<String> STATS = Set.copyOf(Arrays.asList(
            "CUSTOM_MAX_DURABILITY", "BOW_STRENGTH", "ARROW_DAMAGE", "AMMO_CONSUMPTION",
            "ARROW_VELOCITY", "ARROW_ACCURACY", "ARROW_PIERCING", "KNOCKBACK",
            "STUN_CHANCE", "BLEED_CHANCE", "BLEED_DAMAGE", "BLEED_DURATION",
            "CRIT_CHANCE", "CRIT_DAMAGE", "ARMOR_PENETRATION_FLAT",
            "LIGHT_ARMOR_PENETRATION_FLAT", "HEAVY_ARMOR_PENETRATION_FLAT",
            "ARMOR_PENETRATION_FRACTION", "LIGHT_ARMOR_PENETRATION_FRACTION",
            "HEAVY_ARMOR_PENETRATION_FRACTION", "HEAVY_ARMOR_DAMAGE", "LIGHT_ARMOR_DAMAGE",
            "IMMUNITY_BONUS_FRACTION", "IMMUNITY_BONUS_FLAT", "IMMUNITY_REDUCTION",
            "DAMAGE_UNARMED", "DAMAGE_MELEE", "DAMAGE_RANGED", "DAMAGE_ALL",
            "ATTACK_REACH", "VELOCITY_DAMAGE", "DISMOUNT_CHANCE", "DAMAGE_RESISTANCE",
            "EXPLOSION_RESISTANCE", "FALL_DAMAGE_RESISTANCE", "FIRE_RESISTANCE",
            "MAGIC_RESISTANCE", "BLEED_RESISTANCE", "STUN_RESISTANCE", "POISON_RESISTANCE",
            "PROJECTILE_RESISTANCE", "MELEE_RESISTANCE", "DODGE_CHANCE", "HEALING_BONUS",
            "FOOD_CONSUMPTION", "COOLDOWN_REDUCTION", "EXPLOSION_POWER", "CRAFTING_SPEED",
            "ALCHEMY_QUALITY", "ALCHEMY_QUALITY_FRACTION", "ENCHANTING_QUALITY",
            "ENCHANTING_QUALITY_FRACTION", "ANVIL_QUALITY_FLAT", "ANVIL_QUALITY_FRACTION",
            "BREWING_INGREDIENT_CONSUMPTION", "BREWING_SPEED", "POTION_CONSUMPTION",
            "THROWING_VELOCITY", "SMITHING_QUALITY", "SMITHING_QUALITY_FRACTION",
            "MINING_RARE_DROPS", "MINING_DROPS", "WOODCUTTING_RARE_DROPS",
            "WOODCUTTING_DROPS", "DIGGING_RARE_DROPS", "DIGGING_DROPS",
            "FARMING_RARE_DROPS", "FARMING_DROPS", "FISHING_LUCK", "SKILL_EXP_GAIN",
            "VANILLA_EXP_GAIN", "DAMAGE_TAKEN", "REFLECT_CHANCE", "REFLECT_FRACTION",
            "GENERIC_LUCK", "GENERIC_ARMOR", "GENERIC_ARMOR_TOUGHNESS",
            "GENERIC_ATTACK_DAMAGE", "GENERIC_ATTACK_SPEED", "GENERIC_KNOCKBACK_RESISTANCE",
            "GENERIC_MAX_HEALTH", "GENERIC_MOVEMENT_SPEED", "SNEAK_MOVEMENT_SPEED_BONUS",
            "SPRINT_MOVEMENT_SPEED_BONUS", "DAMAGE_EXPLOSION", "DAMAGE_FIRE",
            "DAMAGE_MAGIC", "DAMAGE_POISON", "DAMAGE_BLUDGEONING", "DAMAGE_LIGHTNING",
            "DAMAGE_FREEZING", "DAMAGE_RADIANT", "DAMAGE_NECROTIC", "COOKING_SPEED",
            "JUMP_HEIGHT", "JUMPS", "EXTRA_EXPLOSION_DAMAGE", "EXTRA_FIRE_DAMAGE",
            "EXTRA_MAGIC_DAMAGE", "EXTRA_POISON_DAMAGE", "EXTRA_BLUDGEONING_DAMAGE",
            "EXTRA_LIGHTNING_DAMAGE", "EXTRA_FREEZING_DAMAGE", "EXTRA_RADIANT_DAMAGE",
            "EXTRA_NECROTIC_DAMAGE", "BLUDGEONING_RESISTANCE", "LIGHTNING_RESISTANCE",
            "FREEZING_RESISTANCE", "RADIANT_RESISTANCE", "NECROTIC_RESISTANCE",
            "DURABILITY_MULTIPLIER", "ENTITY_DROPS", "LIGHT_ARMOR", "HEAVY_ARMOR",
            "CRIT_CHANCE_RESISTANCE", "CRIT_DAMAGE_RESISTANCE", "LAPIS_SAVE_CHANCE",
            "ENCHANTING_REFUND_CHANCE", "ENCHANTING_REFUND_FRACTION",
            "LINGERING_DURATION_MULTIPLIER", "LINGERING_RADIUS_MULTIPLIER",
            "SPLASH_INTENSITY_MINIMUM", "ENTITY_RARE_DROPS", "DIG_SPEED", "MINING_SPEED",
            "CROSSBOW_MAGAZINE", "GENERIC_SCALE", "PLAYER_BLOCK_INTERACTION_RANGE",
            "GENERIC_STEP_HEIGHT", "GENERIC_GRAVITY", "GENERIC_SAFE_FALL_DISTANCE",
            "GENERIC_FALL_DAMAGE_MULTIPLIER", "ATTACK_REACH_MULTIPLIER", "SHIELD_DISARMING",
            "LIFE_STEAL", "PVP_RESISTANCE", "DAMAGE_PLAYER", "DAMAGE_MOUNTED",
            "WATER_MOVEMENT_EFFICIENCY", "SUBMERGED_MINING_SPEED", "FLIGHT_SPEED_BONUS",
            "OXYGEN_BONUS", "BACK_PROTECTION", "FRONT_PROTECTION", "DAMAGE_ABSORPTION",
            "HEALTH_BONUS", "HEALTH_MULTIPLIER_BONUS", "MOVEMENT_SPEED_BONUS",
            "KNOCKBACK_RESISTANCE", "ATTACK_DAMAGE_BONUS", "ATTACK_SPEED_BONUS",
            "LUCK_BONUS", "BLOCK_REACH", "STEP_HEIGHT", "SCALE", "GRAVITY",
            "SAFE_FALLING_DISTANCE", "FALL_DAMAGE_MULTIPLIER",
            "WATER_MOVEMENT_EFFICIENCY_BONUS", "SUBMERGED_MINING_SPEED_BONUS"
    ));

    static final Set<String> PERMANENT_EFFECTS = Set.copyOf(Arrays.asList(
            "SPEED", "SLOW", "FAST_DIGGING", "SLOW_DIGGING", "INCREASE_DAMAGE", "HEAL",
            "HARM", "JUMP", "CONFUSION", "REGENERATION", "DAMAGE_RESISTANCE",
            "FIRE_RESISTANCE", "WATER_BREATHING", "INVISIBILITY", "BLINDNESS", "DARKNESS",
            "NIGHT_VISION", "HUNGER", "WEAKNESS", "POISON", "WITHER", "HEALTH_BOOST",
            "ABSORPTION", "SATURATION", "GLOWING", "LEVITATION", "LUCK", "UNLUCK",
            "SLOW_FALLING", "CONDUIT_POWER", "DOLPHINS_GRACE", "BAD_OMEN",
            "HERO_OF_THE_VILLAGE", "INFESTED", "OOZING", "WEAVING", "WIND_CHARGED",
            "CHOCOLATE_MILK", "MILK", "STUN", "FIRE", "BLEED", "ANTIBLEED", "RECALL",
            "CUSTOM_HEAL", "INSTANT_EXPLOSION_DAMAGE", "INSTANT_FIRE_DAMAGE",
            "INSTANT_POISON_DAMAGE", "INSTANT_MAGIC_DAMAGE", "INSTANT_MELEE_DAMAGE",
            "INSTANT_PROJECTILE_DAMAGE", "INSTANT_BLUDGEONING_DAMAGE",
            "INSTANT_LIGHTNING_DAMAGE", "INSTANT_FREEZING_DAMAGE", "INSTANT_RADIANT_DAMAGE",
            "INSTANT_NECROTIC_DAMAGE"
    ));

    private ValhallaKnownValues() {
    }
}
