name: ItemsAdderAdditions
version: '${version}'
main: toutouchien.itemsadderadditions.plugin.ItemsAdderAdditions
loader: toutouchien.itemsadderadditions.plugin.ItemsAdderAdditionsLoader
bootstrapper: toutouchien.itemsadderadditions.plugin.ItemsAdderAdditionsBootstrap
api-version: '${minMinecraftVersion}'
authors: [ PuppyTransGirl ]

dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: true

    PlaceholderAPI:
      load: BEFORE
      required: false

    CoreProtect:
      load: BEFORE
      required: false
